name: 'Build JupyterLite'
description: 'Build JupyterLite from source'
runs:
  using: 'composite'
  steps:
    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Setup pip
      shell: bash
      run: |
        python3 -m pip install --user -U pip setuptools wheel
        python3 -m pip install --group build

    - name: Install JS dependencies
      shell: bash
      run: jlpm install

    - name: Build JS (production)
      shell: bash
      run: jlpm build:prod

    - name: Pack app
      shell: bash
      run: jlpm pack:app

    - name: Build Python packages
      shell: bash
      run: jlpm build:py

    - name: Copy to dist
      shell: bash
      run: jlpm dist:copy
