name: Windows Dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  CACHE_EPOCH: 8
  PYTHONUTF8: 1

jobs:
  win-dev:
    runs-on: windows-latest
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v6

      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Cache (node_modules)
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: node_modules/
          key: |
            ${{ env.CACHE_EPOCH }}-${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Cache (pip)
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: |
            ${{ env.CACHE_EPOCH }}-${{ runner.os }}-pip-dev-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ env.CACHE_EPOCH }}-${{ runner.os }}-pip-dev-
            ${{ env.CACHE_EPOCH }}-${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --group build ruff

      - name: Install JS dependencies
        run: jlpm install

      - name: Build
        run: jlpm build

      - name: Build Python packages
        run: jlpm build:py

      - name: Pack app
        run: jlpm pack:app

      - name: Copy to dist
        run: jlpm dist:copy

      - name: Install (dev)
        run: python -m pip install -e './py/jupyterlite-core[all,test]' -e ./py/jupyterlite

      - name: Lint
        run: jlpm lint
